### PR TITLE
fix: cleanup build

### PR DESCRIPTION
**Pull request by JaeAeich**
## Description

This PR fixes:
- build issues
- lint issues
- turbo pipeline issues

#268 
## Checklist

- [x] My code follows the [contributing guidelines][contributing] of this project.
- [x]  I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code in hard-to-understand areas.
- [x] I have updated the user-facing documentation to describe any new or changed behavior.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by SalihuDickson** [comment]
@JaeAeich, did you pull my PR or did you just rewrite the fixes I msde. I am asking because there are issues with the build scripts that I fixed already but are broken again in the current cleanup PR even though this was merged.

**Comment by SalihuDickson** [comment]
Is there any specifc reason the react dir is being removed after the build. It's already in .gitignore and deleting it just seems like an unnecessary step that makes checking for errors and general debugging a little bit harder. For example you might have noticed that the react components are not being built, at all in the cleanup PR, the typescript compiler just generates their type files after they've been generated and then they are deleted.

**Comment by JaeAeich** [comment]
> Is there any specifc reason the react dir is being removed after the build. It's already in .gitignore and deleting it just seems like an unnecessary step that makes checking for errors and general debugging a little bit harder.

Yeah the since the react dir would still be there, rebuilding without clean would break. Hence had to remove it in the build process itself.
And you PR contained some changes from form component, and I had some changes so I just took reference from that to make some changes, hope thats ok, I thought you were busy and wanted to merge. Please feel free to make any necessary changes to cleanup PR.

**Comment by SalihuDickson** [comment]
> Yeah the since the react dir would still be there, rebuilding without clean would break. Hence had to remove it in the build process itself. And you PR contained some changes from form component, and I had some changes so I just took reference from that to make some changes, hope thats ok, I thought you were busy and wanted to merge. Please feel free to make any necessary changes to cleanup PR.

Well, like I said, the react components are being deleted before every build. The issue was with the order of how  the processes were being completed, more specifically, reading from package json did not block of other processes and allows them start before it is done. And deleting the react dir after every build would not have solved that, it would just mean that tsup would not be able to build the react components. And I only made one change to the form component which was to fix a minor rendering issue.

While I understand the need to get the cleanup PR merged quickly, It might have been better to ask me of the relevance of certain changes before going ahead to cherrypick them and suggest that I rewrite them on a different PR :)

**Comment by JaeAeich** [comment]
My bad, I shouldn't have taken reference but I thought the solution worked and we could improve upon as you made changes because you have worked on build script more, thats why haven't merged cleanup. But def, will keep in mind.

**Pull request merged**
