### PR TITLE
chore(ecc-client-ga4gh-tes): building type files

### PR DESCRIPTION
**Pull request by SalihuDickson**
## Description
This PR builds the type files for the TES package into the dist file

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by JaeAeich** [comment]
LGTM! But maybe since this PR is for minor fixes (form branch name), I would say we should also configure the scripts, IMO they could be formatted a bit better.

@git-anurag-hub and @SalihuDickson how about something like this, maybe we can follow this in all our packages?

```
  "scripts": {
    "dev": "concurrently \"npm run dev:ts\" \"npm run dev:wds\"",
    "dev:ts": "tsc --watch --preserveWatchOutput",
    "dev:wds": "wds",
    "lint": "eslint --ext .ts,.html . --ignore-path .gitignore",
    "lint:fix": "npm run lint -- --fix",
    "test": "concurrently \"npm run test:ts\" \"npm run test:wtr\"",
    "test:ts": "tsc",
    "test:wtr": "wtr --coverage",
    "test:watch": "concurrently \"npm run test:ts\" \"npm run test:wtr:watch\"",
    "test:wtr:watch": "wtr --watch",
    "storybook": "concurrently \"npm run storybook:ts\" \"npm run storybook:wds\"",
    "storybook:ts": "tsc",
    "storybook:wds": "wds -c .storybook/server.mjs",
    "storybook:build": "npm-run-all storybook:ts storybook:analyze build-storybook",
    "storybook:analyze": "cem analyze --fast --exclude dist",
    "build": "tsc",
    "start:build": "web-dev-server --root-dir dist --app-index index.html --open",
    "release": "npm version && npm run build && build publish"
  }
```

**Comment by SalihuDickson** [comment]
> LGTM! But maybe since this PR is for minor fixes (from branch name), I would say we should also configure the scripts, IMO they could be formatted a bit better.
> 
> 
> 
> @git-anurag-hub and @SalihuDickson how about something like this, maybe we can follow this in all our packages?
> 
> 
> 
> ```
> 
>   "scripts": {
> 
>     "dev": "concurrently \"npm run dev:ts\" \"npm run dev:wds\"",
> 
>     "dev:ts": "tsc --watch --preserveWatchOutput",
> 
>     "dev:wds": "wds",
> 
>     "lint": "eslint --ext .ts,.html . --ignore-path .gitignore",
> 
>     "lint:fix": "npm run lint -- --fix",
> 
>     "test": "concurrently \"npm run test:ts\" \"npm run test:wtr\"",
> 
>     "test:ts": "tsc",
> 
>     "test:wtr": "wtr --coverage",
> 
>     "test:watch": "concurrently \"npm run test:ts\" \"npm run test:wtr:watch\"",
> 
>     "test:wtr:watch": "wtr --watch",
> 
>     "storybook": "concurrently \"npm run storybook:ts\" \"npm run storybook:wds\"",
> 
>     "storybook:ts": "tsc",
> 
>     "storybook:wds": "wds -c .storybook/server.mjs",
> 
>     "storybook:build": "npm-run-all storybook:ts storybook:analyze build-storybook",
> 
>     "storybook:analyze": "cem analyze --fast --exclude dist",
> 
>     "build": "tsc",
> 
>     "start:build": "web-dev-server --root-dir dist --app-index index.html --open",
> 
>     "release": "npm version && npm run build && build publish"
> 
>   }
> 
> ``` 

Okay, this was just meant to add type support to the package but I guess it wouldn't hurt to properly format the scripts at the same time 👍🏾

**Comment by JaeAeich** [comment]
@SalihuDickson or maybe since both `ecc-client-ga4gh-tes` and `ecc-client-ga4gh-wes` have the same project schema, we can format the scripts in both/all in one commit.

**Comment by SalihuDickson** [comment]
@JaeAeich, looking at the scripts, i think your suggestion may be overkill and just leads to the scripts becoming unnecessarily bloated. I did some refactoring but they're minor.

**Comment by JaeAeich** [comment]
Hmm.. well this was just a suggestion :sweat_smile: , but maybe @git-anurag-hub can give better comments on this. Just something on your refactor though, why did you remove `--exclude-dist` and can you explain the `release`, I think this might be wrong and also it not running in my system.

**Comment by SalihuDickson** [comment]
> Hmm.. well this was just a suggestion :sweat_smile: , but maybe @git-anurag-hub can give better comments on this. Just something on your refactor though, why did you remove `--exclude-dist` and can you explain the `release`, I think this might be wrong and also it not running in my system. 

I changed the release script by accident (I was comparing some stuff just before I pushed) I'll fix it, and I removed `--exclude-dist` from the storybook scripts cause I moved it to the analyze script

**Comment by JaeAeich** [comment]
@SalihuDickson maybe we shouldn't think about refactoring rn, I have been trying to find a better bundling but seems like what we currently have might bebest as of now, so maybe you can revert the script refactor and merge this.

@git-anurag-hub can you review this asap :+1:

**Review by git-anurag-hub — APPROVED** [review]

**Comment by JaeAeich** [comment]
This has been covered so its better to close the PR. @SalihuDickson

**Pull request closed without merging**
