### PR TITLE
build: build scripts

### PR DESCRIPTION
**Pull request by SalihuDickson**
## Description
This PR expands the current utils package design solution to work to make it compatible with all the elixir cloud components provided they meet a short list of requirements

Fixes #(issue)

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by JaeAeich** [comment]
The react component seems to work :partying_face:, but there are these couple of issues that I am facing:
1) **`Import path`**: `shoelace` has the complete path without `index.js` but here lets say I want to import just the form component I have two ways, either import from `dist/react` as import or from `dist/react/form/index.js` as default import. Are we expecting all the users to import components from `dist/react`?
2) **`Type definition`**: Type of the props are missing, how do I import them to type annotate my props? 
jaeaeich-design-code-sample
3) **`CSS`**: I don't know why this is happening,  I used vite to test the app, and its default CSS was able to penetrate `shadow dom` :fearful:, this might be very problematic. Note the labels are **NOT** supposed to be center aligned. Being able to resize the component makes sense but how is the CSS of label getting affected?
jaeaeich-design-form
demo-form

Also please update the package-lock.json file. And for some reason on running `build` it makes changes in `packages/ecc-utils-design/custom-elements-manifest.config.js`.
---
If anyone wants to test the package as well [here](https://www.npmjs.com/package/jaeaeich-design) is the test design npm package I published :+1: ,
or just run:

```bash
npm i jaeaeich-design
```
// @SalihuDickson @git-anurag-hub

**Comment by SalihuDickson** [comment]
@JaeAeich, 
1. The ideal method of importing would be as a default import i.e from `@elixir-cloud/design/dist/react/form/index.js`. This way you don't execute the index folder in the react root. The issue with executing that file is that we register all components when they are imported, essentially making tree shaking pointless.
2. Thanks for bringing this up, We actually need to export all our types from where they are defined. But that brings me to another issue. After exporting you would normally need to import from the file where they are defined. For example, if you want to import field, you would have to do it like this `import type { Field } from '@elixir-cloud/design/dist/components/form/form';` Issue with this is having to know where to export each type from. But we can solve this by exporting all types from "/dist/index.js", this is simple enough but we need to rename our types with some specificity to avoid conflicts. I think the second solution makes more sense. @git-anurag-hub, maybe you could weigh in here.
3. Yh, when the components are registered as react components i think they lose the isolation provided by the shadow DOM, as react does not natively support shadow DOMencapsulation (same thing happens with shoelace components). Perhaps the user can use the javascript API to reinforce the shadow DOM. This however causes other issues, so it might not be a good idea to do that on our end while generating the react components.

Thanks for your detailed review.

**Comment by SalihuDickson** [comment]
hey @git-anurag-hub, can you please check the vercel logs and help me figure out why the deployment is failing?

**Comment by JaeAeich** [comment]
@SalihuDickson 
- Types export works we will just have to document that even in react the user will have to import the types from `../dist/components/..` even if the component was imported from `../dist/react/..`.
- Styles are really messed up in react, which is something we should really look into otherwise app author will be constrained by us in implementing there design. @git-anurag-hub ?

**Comment by git-anurag-hub** [comment]
> hey @git-anurag-hub, can you please check the vercel logs and help me figure out why the deployment is failing?

Hey @SalihuDickson, here are the logs to debug!
```
[00:19:42.041] Running build in Washington, D.C., USA (East) – iad1
[00:19:42.175] Cloning github.com/elixir-cloud-aai/cloud-components (Branch: build-scripts, Commit: 31ffa6e)
[00:19:42.195] Skipping build cache, deployment was triggered without cache.
[00:19:42.701] Cloning completed: 525.994ms
[00:19:43.021] Running "vercel build"
[00:19:43.495] Vercel CLI 33.5.3
[00:19:43.654] > Detected Turbo. Adjusting default settings...
[00:19:44.169] Running "install" command: `npm install --prefix=../..`...
[00:21:28.326] 
[00:21:28.327] > elixir-cloud-components@2.0.0 prepare
[00:21:28.328] > husky install
[00:21:28.328] 
[00:21:28.415] husky - Git hooks installed
[00:21:28.462] 
[00:21:28.463] added 3636 packages, and audited 3650 packages in 2m
[00:21:28.463] 
[00:21:28.463] 422 packages are looking for funding
[00:21:28.464]   run `npm fund` for details
[00:21:28.558] 
[00:21:28.558] 32 vulnerabilities (13 moderate, 19 high)
[00:21:28.558] 
[00:21:28.558] To address issues that do not require attention, run:
[00:21:28.558]   npm audit fix
[00:21:28.558] 
[00:21:28.559] To address all issues (including breaking changes), run:
[00:21:28.559]   npm audit fix --force
[00:21:28.559] 
[00:21:28.559] Run `npm audit` for details.
[00:21:28.663] Turborepo did not find the correct binary for your platform.
[00:21:28.669] We will attempt to install it now.
[00:21:30.040] Installation has succeeded.
[00:21:30.575] • Packages in scope: ecc-docs
[00:21:30.576] • Running build in 1 packages
[00:21:30.576] • Remote caching enabled
[00:21:30.577] @elixir-cloud/design:build: cache bypass, force executing c1c0a55d1c099258
[00:21:30.907] @elixir-cloud/design:build: 
[00:21:30.907] @elixir-cloud/design:build: > @elixir-cloud/design@0.0.1 build
[00:21:30.907] @elixir-cloud/design:build: > node ../../scripts/build.js
[00:21:30.907] @elixir-cloud/design:build: 
[00:21:31.378] @elixir-cloud/design:build: Cleaning up previous build ...
[00:21:31.380] @elixir-cloud/design:build: installing dependencies ...
[00:21:31.382] @elixir-cloud/design:build: Generating CEM config ...
[00:21:31.618] @elixir-cloud/design:build: Generating component metadata ...
[00:21:32.167] @elixir-cloud/design:build: (node:763) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
[00:21:32.168] @elixir-cloud/design:build: (Use `node --trace-warnings ...` to show where the warning was created)
[00:21:32.170] @elixir-cloud/design:build: (node:763) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[00:21:32.429] @elixir-cloud/design:build: [vs-code-custom-data-generator] - Generating config files...
[00:21:32.502] @elixir-cloud/design:build: [34m[vs-code-custom-data-generator] - Generated "dist/vscode.html-custom-data.json".[0m
[00:21:32.502] @elixir-cloud/design:build: [32m[vs-code-custom-data-generator] - File generation complete.[0m
[00:21:32.503] @elixir-cloud/design:build: [jet-brains-web-type-generator] - Generating config files...
[00:21:32.520] @elixir-cloud/design:build: [34m[jet-brains-web-type-generator] - Generated "dist/web-types.json".[0m
[00:21:32.521] @elixir-cloud/design:build: [32m[jet-brains-web-type-generator] - File generation complete.[0m
[00:21:32.682] @elixir-cloud/design:build: [6:51:32 PM] @custom-elements-manifest/analyzer: Created new manifest.
[00:21:32.720] @elixir-cloud/design:build: Wrapping components for React ...
[00:21:32.721] @elixir-cloud/design:build: Running the TypeScript compiler ...
[00:21:35.833] @elixir-cloud/design:build: Building source ...
[00:21:35.842] @elixir-cloud/design:build: (node:742) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
[00:21:35.843] @elixir-cloud/design:build: (Use `node --trace-warnings ...` to show where the warning was created)
[00:21:36.166] @elixir-cloud/design:build: (node:742) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[00:21:36.186] @elixir-cloud/design:build: CLI Building entry: /vercel/path0/packages/ecc-utils-design/src/index.ts, /vercel/path0/packages/ecc-utils-design/src/components/index.ts, /vercel/path0/packages/ecc-utils-design/src/components/collection/collection.styles.ts, /vercel/path0/packages/ecc-utils-design/src/components/collection/collection.ts, /vercel/path0/packages/ecc-utils-design/src/components/collection/index.ts, /vercel/path0/packages/ecc-utils-design/src/components/details/details.ts, /vercel/path0/packages/ecc-utils-design/src/components/details/index.ts, /vercel/path0/packages/ecc-utils-design/src/components/form/form.styles.ts, /vercel/path0/packages/ecc-utils-design/src/components/form/form.ts, /vercel/path0/packages/ecc-utils-design/src/components/form/index.ts, /vercel/path0/packages/ecc-utils-design/src/react/index.ts, /vercel/path0/packages/ecc-utils-design/src/react/collection/index.ts, /vercel/path0/packages/ecc-utils-design/src/react/details/index.ts, /vercel/path0/packages/ecc-utils-design/src/react/form/index.ts, /vercel/path0/packages/ecc-utils-design/src/utilities/general.ts, /vercel/path0/packages/ecc-utils-design/src/utilities/index.ts
[00:21:36.187] @elixir-cloud/design:build: CLI Using tsconfig: tsconfig.json
[00:21:36.187] @elixir-cloud/design:build: CLI tsup v8.0.1
[00:21:36.189] @elixir-cloud/design:build: CLI Target: es2017
[00:21:36.191] @elixir-cloud/design:build: ESM Build start
[00:21:36.296] @elixir-cloud/design:build: Generated an empty chunk: "chunk.O6ACWJOD".
[00:21:36.299] @elixir-cloud/design:build: Generated an empty chunk: "chunk.Q3V7SUHZ".
[00:21:36.420] @elixir-cloud/design:build: ESM dist/react/index.js                             530.00 B
[00:21:36.421] @elixir-cloud/design:build: ESM dist/react/collection/index.js                  244.00 B
[00:21:36.421] @elixir-cloud/design:build: ESM dist/react/details/index.js                     200.00 B
[00:21:36.421] @elixir-cloud/design:build: ESM dist/chunks/chunk.DNXL4TGA.js                   543.00 B
[00:21:36.421] @elixir-cloud/design:build: ESM dist/react/form/index.js                        238.00 B
[00:21:36.421] @elixir-cloud/design:build: ESM dist/components/form/index.js                   238.00 B
[00:21:36.422] @elixir-cloud/design:build: ESM dist/components/form/form.js                    203.00 B
[00:21:36.422] @elixir-cloud/design:build: ESM dist/chunks/chunk.YVYDG5FB.js                   649.00 B
[00:21:36.422] @elixir-cloud/design:build: ESM dist/utilities/general.js                       106.00 B
[00:21:36.422] @elixir-cloud/design:build: ESM dist/utilities/index.js                         144.00 B
[00:21:36.422] @elixir-cloud/design:build: ESM dist/chunks/chunk.IETTPWXN.js                   508.00 B
[00:21:36.422] @elixir-cloud/design:build: ESM dist/index.js                                   631.00 B
[00:21:36.427] @elixir-cloud/design:build: ESM dist/chunks/chunk.O6ACWJOD.js                   1.00 B
[00:21:36.428] @elixir-cloud/design:build: ESM dist/components/index.js                        568.00 B
[00:21:36.429] @elixir-cloud/design:build: ESM dist/chunks/chunk.Q3V7SUHZ.js                   1.00 B
[00:21:36.429] @elixir-cloud/design:build: ESM dist/chunks/chunk.EQPB4CSO.js                   519.00 B
[00:21:36.429] @elixir-cloud/design:build: ESM dist/chunks/chunk.6BY5M2UD.js                   231.00 B
[00:21:36.429] @elixir-cloud/design:build: ESM dist/chunks/chunk.XSRGDEVC.js                   16.90 KB
[00:21:36.429] @elixir-cloud/design:build: ESM dist/components/collection/collection.styles.js 128.00 B
[00:21:36.430] @elixir-cloud/design:build: ESM dist/components/collection/collection.js        209.00 B
[00:21:36.430] @elixir-cloud/design:build: ESM dist/components/collection/index.js             244.00 B
[00:21:36.430] @elixir-cloud/design:build: ESM dist/chunks/chunk.7CBYHTSI.js                   279.00 B
[00:21:36.430] @elixir-cloud/design:build: ESM dist/chunks/chunk.3AFJJAPJ.js                   8.51 KB
[00:21:36.430] @elixir-cloud/design:build: ESM dist/chunks/chunk.VFZ2JH7G.js                   991.00 B
[00:21:36.430] @elixir-cloud/design:build: ESM dist/components/details/details.js              165.00 B
[00:21:36.431] @elixir-cloud/design:build: ESM dist/components/details/index.js                200.00 B
[00:21:36.431] @elixir-cloud/design:build: ESM dist/chunks/chunk.SNIO7BGJ.js                   252.00 B
[00:21:36.431] @elixir-cloud/design:build: ESM dist/chunks/chunk.Y7JL364H.js                   39.66 KB
[00:21:36.431] @elixir-cloud/design:build: ESM dist/components/form/form.styles.js             122.00 B
[00:21:36.431] @elixir-cloud/design:build: ESM dist/chunks/chunk.WMPJ47FS.js                   1.62 KB
[00:21:36.432] @elixir-cloud/design:build: ESM dist/chunks/chunk.7VONTVYH.js                   526.00 B
[00:21:36.432] @elixir-cloud/design:build: ESM dist/chunks/chunk.LCR2KDCX.js                   14.95 KB
[00:21:36.433] @elixir-cloud/design:build: ESM ⚡️ Build success in 230ms
[00:21:36.473] @elixir-cloud/lit-tes:build: cache bypass, force executing 6fd8cf0ec467ba55
[00:21:36.474] @elixir-cloud/lit-wes:build: cache bypass, force executing 4c0166705cd690a4
[00:21:36.990] @elixir-cloud/lit-tes:build: 
[00:21:36.991] @elixir-cloud/lit-tes:build: > @elixir-cloud/lit-tes@0.0.0 build
[00:21:36.991] @elixir-cloud/lit-tes:build: > node ../../scripts/build.js
[00:21:36.991] @elixir-cloud/lit-tes:build: 
[00:21:37.000] @elixir-cloud/lit-wes:build: 
[00:21:37.000] @elixir-cloud/lit-wes:build: > @elixir-cloud/lit-wes@0.0.0 build
[00:21:37.000] @elixir-cloud/lit-wes:build: > node ../../scripts/build.js
[00:21:37.000] @elixir-cloud/lit-wes:build: 
[00:21:37.644] @elixir-cloud/lit-tes:build: Cleaning up previous build ...
[00:21:37.646] @elixir-cloud/lit-tes:build: installing dependencies ...
[00:21:37.648] @elixir-cloud/lit-tes:build: Generating CEM config ...
[00:21:37.656] @elixir-cloud/lit-wes:build: Cleaning up previous build ...
[00:21:37.657] @elixir-cloud/lit-wes:build: installing dependencies ...
[00:21:37.660] @elixir-cloud/lit-wes:build: Generating CEM config ...
[00:21:38.000] @elixir-cloud/lit-tes:build: Generating component metadata ...
[00:21:38.009] @elixir-cloud/lit-wes:build: Generating component metadata ...
[00:21:38.758] @elixir-cloud/lit-tes:build: (node:874) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
[00:21:38.760] @elixir-cloud/lit-tes:build: (Use `node --trace-warnings ...` to show where the warning was created)
[00:21:38.761] @elixir-cloud/lit-tes:build: (node:874) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[00:21:38.886] @elixir-cloud/lit-wes:build: (node:887) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
[00:21:38.886] @elixir-cloud/lit-wes:build: (Use `node --trace-warnings ...` to show where the warning was created)
[00:21:38.890] @elixir-cloud/lit-wes:build: (node:887) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[00:21:39.107] @elixir-cloud/lit-tes:build: [vs-code-custom-data-generator] - Generating config files...
[00:21:39.193] @elixir-cloud/lit-wes:build: [vs-code-custom-data-generator] - Generating config files...
[00:21:39.212] @elixir-cloud/lit-tes:build: [34m[vs-code-custom-data-generator] - Generated "dist/vscode.html-custom-data.json".[0m
[00:21:39.213] @elixir-cloud/lit-tes:build: [32m[vs-code-custom-data-generator] - File generation complete.[0m
[00:21:39.213] @elixir-cloud/lit-tes:build: [jet-brains-web-type-generator] - Generating config files...
[00:21:39.227] @elixir-cloud/lit-tes:build: [34m[jet-brains-web-type-generator] - Generated "dist/web-types.json".[0m
[00:21:39.227] @elixir-cloud/lit-tes:build: [32m[jet-brains-web-type-generator] - File generation complete.[0m
[00:21:39.245] @elixir-cloud/lit-tes:build: [6:51:39 PM] @custom-elements-manifest/analyzer: Created new manifest.
[00:21:39.267] @elixir-cloud/lit-tes:build: Wrapping components for React ...
[00:21:39.268] @elixir-cloud/lit-tes:build: Running the TypeScript compiler ...
[00:21:39.300] @elixir-cloud/lit-wes:build: [34m[vs-code-custom-data-generator] - Generated "dist/vscode.html-custom-data.json".[0m
[00:21:39.301] @elixir-cloud/lit-wes:build: [32m[vs-code-custom-data-generator] - File generation complete.[0m
[00:21:39.301] @elixir-cloud/lit-wes:build: [jet-brains-web-type-generator] - Generating config files...
[00:21:39.321] @elixir-cloud/lit-wes:build: [34m[jet-brains-web-type-generator] - Generated "dist/web-types.json".[0m
[00:21:39.321] @elixir-cloud/lit-wes:build: [32m[jet-brains-web-type-generator] - File generation complete.[0m
[00:21:39.340] @elixir-cloud/lit-wes:build: [6:51:39 PM] @custom-elements-manifest/analyzer: Created new manifest.
[00:21:39.366] @elixir-cloud/lit-wes:build: Wrapping components for React ...
[00:21:39.366] @elixir-cloud/lit-wes:build: Running the TypeScript compiler ...
[00:21:44.873] @elixir-cloud/lit-wes:build: Building source ...
[00:21:44.882] @elixir-cloud/lit-tes:build: Building source ...
[00:21:44.883] @elixir-cloud/lit-wes:build: (node:833) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
[00:21:44.884] @elixir-cloud/lit-wes:build: (Use `node --trace-warnings ...` to show where the warning was created)
[00:21:44.897] @elixir-cloud/lit-tes:build: (node:832) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
[00:21:44.898] @elixir-cloud/lit-tes:build: (Use `node --trace-warnings ...` to show where the warning was created)
[00:21:45.377] @elixir-cloud/lit-wes:build: (node:833) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[00:21:45.378] @elixir-cloud/lit-tes:build: (node:832) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[00:21:45.390] @elixir-cloud/lit-wes:build: CLI Building entry: /vercel/path0/packages/ecc-client-lit-ga4gh-wes/src/index.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-wes/src/components/index.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-wes/src/components/runs/index.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-wes/src/components/runs/runs.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-wes/src/components/wes-create-run/index.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-wes/src/components/wes-create-run/wes-create-run.ts
[00:21:45.392] @elixir-cloud/lit-wes:build: CLI Using tsconfig: tsconfig.json
[00:21:45.392] @elixir-cloud/lit-wes:build: CLI tsup v8.0.1
[00:21:45.394] @elixir-cloud/lit-wes:build: CLI Target: es2017
[00:21:45.396] @elixir-cloud/lit-wes:build: ESM Build start
[00:21:45.397] @elixir-cloud/lit-tes:build: CLI Building entry: /vercel/path0/packages/ecc-client-lit-ga4gh-tes/src/index.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-tes/src/components/index.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-tes/src/components/runs/index.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-tes/src/components/runs/runs.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-tes/src/components/tes-create-run/create-run.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-tes/src/components/tes-create-run/index.ts, /vercel/path0/packages/ecc-client-lit-ga4gh-tes/src/components/tes-create-run/types.d.ts
[00:21:45.399] @elixir-cloud/lit-tes:build: CLI Using tsconfig: tsconfig.json
[00:21:45.402] @elixir-cloud/lit-tes:build: CLI tsup v8.0.1
[00:21:45.405] @elixir-cloud/lit-tes:build: CLI Target: es2017
[00:21:45.407] @elixir-cloud/lit-tes:build: ESM Build start
[00:21:45.439] @elixir-cloud/lit-tes:build: ✘ [ERROR] Could not resolve "./types.js"
[00:21:45.440] @elixir-cloud/lit-tes:build: 
[00:21:45.440] @elixir-cloud/lit-tes:build:     src/components/tes-create-run/index.ts:4:14:
[00:21:45.440] @elixir-cloud/lit-tes:build:       4 │ export * from "./types.js"; // export types from type.d.ts where on...
[00:21:45.440] @elixir-cloud/lit-tes:build:         ╵               ~~~~~~~~~~~~
[00:21:45.441] @elixir-cloud/lit-tes:build: 
[00:21:45.445] @elixir-cloud/lit-tes:build: ESM Build failed
[00:21:45.451] @elixir-cloud/lit-tes:build: /vercel/path0/node_modules/esbuild/lib/main.js:1649
[00:21:45.451] @elixir-cloud/lit-tes:build:   let error = new Error(text);
[00:21:45.452] @elixir-cloud/lit-tes:build:               ^
[00:21:45.452] @elixir-cloud/lit-tes:build: 
[00:21:45.452] @elixir-cloud/lit-tes:build: Error: Build failed with 1 error:
[00:21:45.452] @elixir-cloud/lit-tes:build: src/components/tes-create-run/index.ts:4:14: ERROR: Could not resolve "./types.js"
[00:21:45.452] @elixir-cloud/lit-tes:build:     at failureErrorWithLog (/vercel/path0/node_modules/esbuild/lib/main.js:1649:15)
[00:21:45.452] @elixir-cloud/lit-tes:build:     at /vercel/path0/node_modules/esbuild/lib/main.js:1058:25
[00:21:45.453] @elixir-cloud/lit-tes:build:     at runOnEndCallbacks (/vercel/path0/node_modules/esbuild/lib/main.js:1484:45)
[00:21:45.453] @elixir-cloud/lit-tes:build:     at buildResponseToResult (/vercel/path0/node_modules/esbuild/lib/main.js:1056:7)
[00:21:45.453] @elixir-cloud/lit-tes:build:     at /vercel/path0/node_modules/esbuild/lib/main.js:1085:16
[00:21:45.453] @elixir-cloud/lit-tes:build:     at responseCallbacks.<computed> (/vercel/path0/node_modules/esbuild/lib/main.js:703:9)
[00:21:45.453] @elixir-cloud/lit-tes:build:     at handleIncomingPacket (/vercel/path0/node_modules/esbuild/lib/main.js:762:9)
[00:21:45.453] @elixir-cloud/lit-tes:build:     at Socket.readFromStdout (/vercel/path0/node_modules/esbuild/lib/main.js:679:7)
[00:21:45.454] @elixir-cloud/lit-tes:build:     at Socket.emit (node:events:517:28)
[00:21:45.454] @elixir-cloud/lit-tes:build:     at addChunk (node:internal/streams/readable:335:12) {
[00:21:45.454] @elixir-cloud/lit-tes:build:   errors: [Getter/Setter],
[00:21:45.454] @elixir-cloud/lit-tes:build:   warnings: [Getter/Setter]
[00:21:45.454] @elixir-cloud/lit-tes:build: }
[00:21:45.456] @elixir-cloud/lit-tes:build: 
[00:21:45.457] @elixir-cloud/lit-tes:build: Node.js v18.18.2
[00:21:45.469] @elixir-cloud/lit-tes:build: npm ERR! Lifecycle script `build` failed with error: 
[00:21:45.469] @elixir-cloud/lit-tes:build: npm ERR! Error: command failed 
[00:21:45.470] @elixir-cloud/lit-tes:build: npm ERR!   in workspace: @elixir-cloud/lit-tes@0.0.0 
[00:21:45.470] @elixir-cloud/lit-tes:build: npm ERR!   at location: /vercel/path0/packages/ecc-client-lit-ga4gh-tes 
[00:21:45.474] @elixir-cloud/lit-wes:build: Generated an empty chunk: "chunk.EDOYU2FL".
[00:21:45.482] @elixir-cloud/lit-tes:build: ERROR: command finished with error: command (/vercel/path0/packages/ecc-client-lit-ga4gh-tes) npm run build exited (1)
[00:21:45.494] @elixir-cloud/lit-tes#build: command (/vercel/path0/packages/ecc-client-lit-ga4gh-tes) npm run build exited (1)
[00:21:45.494] 
[00:21:45.495]   Tasks:    1 successful, 3 total
[00:21:45.495]  Cached:    0 cached, 3 total
[00:21:45.495]    Time:    15.44s 
[00:21:45.495] Summary:    /vercel/path0/.turbo/runs/2dBqbYu3shEJSSPrRocZZBo6UHe.json
[00:21:45.495]  Failed:    @elixir-cloud/lit-tes#build
[00:21:45.495] 
[00:21:45.495]  ERROR  run failed: command  exited (1)
[00:21:45.504] Error: Command "turbo run build" exited with 1
[00:21:46.238] 
```

**Comment by SalihuDickson** [comment]
@git-anurag-hub @JaeAeich, I've fixed the conflicts, please review.

**Comment by JaeAeich** [comment]
LGTM @SalihuDickson :rocket: 
Just a query, do you have any thoughts on how we are going to reuse theses in other packages or will we have to copy paste stuff, which definitely isn't a good idea.

**Review by JaeAeich — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
