### PR TITLE
fix(docs): docs improvements

### LINKED ISSUE #142: feat: Documentation

### PR DESCRIPTION
**Pull request by git-anurag-hub**
## Description

Fixes #142 

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by git-anurag-hub** [comment]
New Fixed UI can be found here @uniqueg. https://cloud-components-git-docs-improv-elixir-cloud-aai.vercel.app/

**Comment by JaeAeich** [comment]
@git-anurag-hub Ig it would be better if we had prettier for docs. Since it is just the start of the docs code there wont be so many changes. Plus we will have a set way wrtting of docs. I proposed to add `prettier --write` as `link:fix` script as well.
What do you think?

**Comment by git-anurag-hub** [comment]
> @git-anurag-hub Ig it would be better if we had prettier for docs. Since it is just the start of the docs code there wont be so many changes. Plus we will have a set way wrtting of docs. I proposed to add `prettier --write` as `link:fix` script as well. What do you think?

Sure @JaeAeich you can add that here!

**Comment by git-anurag-hub** [comment]
Hey @uniqueg, I need to add some docs for the design package & make a merge. So I am gonna go ahead & merge this PR. While I think docs are now good we can address the further issues in the other iteration of the docs. 
Latest of the docs can be found here: https://elixir-cloud-components.vercel.app/

**Pull request merged**
