### PR TITLE
feat: responsive submit button

### PR DESCRIPTION
**Pull request by psankhe28**
## Description
Disabled the submit button until all the required fields are filled. Also, made the font as bold for the Submit button text.

Fixes #(issue)
#175 

## Checklist

- [x] My code follows the [contributing guidelines][contributing] of this project.
- [x] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

### CODE REVIEW

**Comment by uniqueg** [comment]
Thanks @psankhe28 - please don't forget to request reviewers (Javed, Anurag and/or Salihu). But first, see if you can fix those failing linter checks.

**Comment by psankhe28** [comment]
> Thanks @psankhe28 - please don't forget to request reviewers (Javed, Anurag and/or Salihu). But first, see if you can fix those failing linter checks.

I tried fixing the linter issues, but not able to do so.

**Comment by uniqueg** [comment]
Please ask for help on Slack (post the GH Actions error messages/logs and a link to this PR)

**Comment by SalihuDickson** [comment]
> > Thanks @psankhe28 - please don't forget to request reviewers (Javed, Anurag and/or Salihu). But first, see if you can fix those failing linter checks.
> 
> I tried fixing the linter issues, but not able to do so.

Great work @psankhe28. I'll review this, if it works okay then i'll fix the linting issue and approve for merge.

**Comment by SalihuDickson** [comment]
@psankhe28, your current solution works fine for basic test cases. However, when the required fields are in a group or array element then the check does not work. While trying to cover the more complex test cases perhaps you could also implement a method that isn't just iterating through all the fields, especially because lit already does this when running the `render` method so you could just add your checks to that instead of iterating through the entire list of fields on each call of the render method and unnecessarily increasing the time complexity.

**Comment by psankhe28** [comment]
> @psankhe28, your current solution works fine for basic test cases. However, when the required fields are in a group or array element then the check does not work. While trying to cover the more complex test cases perhaps you could also implement a method that isn't just iterating through all the fields, especially because lit already does this when running the `render` method so you could just add your checks to that instead of iterating through the entire list of fields on each call of the render method and unnecessarily increasing the time complexity.

Ok, I will make the necessary changes.

**Comment by SalihuDickson** [comment]
@psankhe28, I went ahead and made fixes. Sorry for bypassing on your PR but i needed to finish the implementation because it was blocking one of the test cases i am currently implementing and I didn't want to have to come back to it.

**Review by SalihuDickson — APPROVED** [review]

**Pull request merged**
