### PR TITLE
feat: Package for TES dashboard components

### LINKED ISSUE #48: feat: Package for TES dashboard components
**Is your feature request related to a problem? Please describe.**
There is no package for the dashboard Web Component for Workflow and Task runs. 

**Describe the solution you'd like**
Create separate packages which provide  user friendly Web Components for [TES](https://github.com/ga4gh/task-execution-schemas) and [WES](https://github.com/ga4gh/workflow-execution-service-schemas). These components will provide an easy interface bypassing the programmatical approach to execute complex bioinformatics pipelines (selecting input
files, choosing from pre-configured analysis workflows, and customizing the parameters and
settings for the workflow and task) all without having to write code.

**Acknowledgement**

> We thank you for your valuable contribution and would like to acknowledge it
> on our [contributors][contributors] page. To help us with that, we would like
> to kindly request that you help us with this by commenting on this issue with
> a request to the [@all-contributors bot][all-contributors-bot] of the form
> `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1, TYPE_2, ...`, where
> `TYPE_1` etc. refer to [contribution types supported by the All Contributors
> Specification][all-contributors-types], e.g., `idea`.

[all-contributors-bot]: <https://allcontributors.org/docs/en/bot/overview>
[all-contributors-types]: <https://allcontributors.org/docs/en/emoji-key>
[contributors]: ../../CONTRIBUTORS

### PR DESCRIPTION
**Pull request by JaeAeich**
## Description

This PR add a basic setup for creating dashboard components for WES and TES.

- Fixes #48 

## Checklist

- [x] My code follows the [contributing guidelines][contributing] of this
      project, including, in particular, with regard to any style guidelines
- [x] The title of my PR complies with the [Conventional Commits
      specification][conventional-commits]; in particular, it clearly indicates
      that a change is a breaking change
- [x] I am aware that all my commits will be squashed into a single commit,
      using the PR title as the commit message.
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have updated the user-facing documentation to describe any new or
      changed behavior
- [ ] I have added type annotations for all function/class/method interfaces
      or updated existing ones
- [ ] I have provided [JSDoc][jsdoc] block tags for all
      functions/classes/methods or updated existing ones
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage
- [ ] I have asked the [@all-contributors bot][all-contributors-bot] to
      acknowledge my contributions by commenting on this PR with a request of
      the form `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1,
    TYPE_2, ...`, where `TYPE_1` etc. refer to [contribution types supported
      by the All Contributors Specification][all-contributors-types] OR I do
      not want my contributions to be acknowledged

[all-contributors-bot]: https://allcontributors.org/docs/en/bot/overview
[all-contributors-types]: https://allcontributors.org/docs/en/emoji-key
[contributing]: CONTRIBUTING.md
[conventional-commits]: https://www.conventionalcommits.org/en/v1.0.0/
[jsdoc]: https://jsdoc.app/index.html

### CODE REVIEW

**Comment by JaeAeich** [comment]
@git-anurag-hub Can you please comment on the setup, any improvements or changes I can make here?

**Comment by uniqueg** [comment]
I'm not in a good position to review, @git-anurag-hub or @SalihuDickson would indeed be better suited. But please see my comment in the corresponding issue for a general remark here.

**Comment by SalihuDickson** [comment]
I noticed you're not using a bundler. This might not be a good idea as simply using a dev server doesn't give you the advantage of tree shaking, among other things. In addition to making your development process more difficult cause it means all the tree shakable modules in every package you use will load up completely even when they're not needed, it'll also make working with your code to make updates unnecessarily difficult for anyone that clones this repo and tries to make updates later.

**Comment by JaeAeich** [comment]
@git-anurag-hub @uniqueg, should I close this PR and create it a new one with official FAST CLI, as this is on a diff config and after the templating issue is resolved and `ecc-ui-utils` is set up so that all the packages are consistent?

**Comment by git-anurag-hub** [comment]
Sure @JaeAeich !

**Comment by git-anurag-hub** [comment]
@JaeAeich, can you please list out some of the pros & cons of the open-wc implementation & the fast-cli implementation? I just want to see which one is actually better & suits us!

**Comment by JaeAeich** [comment]
@git-anurag-hub @SalihuDickson 
On paper, there isn't much difference, but I found the official [FAST CLI](https://github.com/microsoft/fast-cli) to be buggy while there were fewer such cases with [open-wc](https://github.com/microsoft/fast-cli) and the gh community is more actively fixing bugs, the definite pro that I found while making components with open-wc wrt FAST one was a better file str configured, better testing support as playwright is not web component specific, more tooling for creating comps like cem analyser. The cons would be that it favors LIT out of the box though after configuring for FAST it works as expected but I still couldn't remove some LIT console logs (but this is not doesn't affect the code afaik). Also FAST CLI gives a setup which extends FoundationElement but our use case requires FastElements again this is not a deal breaker, but this requires more configuration ig after initialisation as I couldn't create component extending FastElement but was able to do so easily in open-wc, look into this [config](https://github.com/JaeAeich/Test-repo).

Apart from that FAST CLI test script doesn't work and there is still an unresolved open issue for adding [new components](https://github.com/microsoft/fast-cli/issues/111).

This is my opinion after working with both the tools.

**Pull request closed without merging**
