### PR TITLE
feat:RO-Crate Dataset-entity

### PR DESCRIPTION
**Pull request by sivangbagri**
## Description

Dedicated PR for RO-Crate Dataset entity 

## Checklist

- [x] My code follows the [contributing guidelines][contributing] of this project.
- [x] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

## Summary by Sourcery

Add a new RO-Crate Dataset entity component to the ecc-client-elixir-ro-crate package, featuring a tabbed interface for managing dataset metadata, related entities, and structure. Include demo HTML files to demonstrate component usage.

New Features:
- Introduce a new RO-Crate Dataset entity component in the ecc-client-elixir-ro-crate package, allowing for detailed dataset metadata management.

Enhancements:
- Implement a tabbed interface for managing dataset metadata, related people, organizations, and structure within the RO-Crate component.

Documentation:
- Add demo HTML files to showcase the usage of the new RO-Crate Dataset entity component.

### CODE REVIEW

**Comment by SalihuDickson** [comment]
1. Okay, that makes sense. I do think it will be a good idea to add options in the future.
2. If you haven't already then you might want to create an issue for that.

**Comment by sivangbagri** [comment]
@SalihuDickson Kindly checkout the new PR

**Comment by SalihuDickson** [comment]
I'll review the other PR ASAP, however this one is just about ready to merge, if you can just take out the type field, and change the tab name to `Dataset Entity`.

**Comment by SalihuDickson** [comment]
Also please resolve conflicts with main.

**Comment by SalihuDickson** [comment]
Hey, Shivang. This looks good so far. I made some changes to the logic handling the conditional license fields. The former logic was pretty convoluted and would break under certain conditions. 

then about the `type` field. Perhaps removing it completely could cause some confusion and make the user believe there's no `type` property. I am going to write an issue requesting support for readonly fields in the form component, we can then use that to signify that there is a type field present but it is uneditable.

**Review by SalihuDickson — APPROVED** [review]

**Pull request merged**
