### PR TITLE
fix: add dynamic min height for group components

### LINKED ISSUE #377: bug: Adjust group component height to accommodate the options for the select field
## Description

When there is only a select component inside the group template the height of the container is too small such that the options are not properly displayed forcing them to become distorted.

## Possible solution(s)

adjust the styles of the select component when it is in the group component so as to force the group component to expand enough to properly fit its options.

### PR DESCRIPTION
**Pull request by SalihuDickson**
## Description

Fixes #377 

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

## Summary by Sourcery

Bug Fixes:
- Add dynamic minimum height for group components to ensure consistent layout.

### CODE REVIEW

**Review by anuragxxd — APPROVED** [review]
lgtm again @SalihuDickson, can you please add the changeset for this too! Thanks.

**Comment by SalihuDickson** [comment]
@anuragxxd, I've added the changeset, please review.

**Comment by anuragxxd** [comment]
Hey @SalihuDickson, I can now only see the change-log & no other changes. What can be the case? Are you sure no changes are being missed due to the merge conflicts or git?

**Comment by SalihuDickson** [comment]
yh, it seems i might have accidentally effected the same changes the other PR i merged, so pulling the changes from main made this PR effectively useless. I'll go ahead and close it.

**Pull request closed without merging**
