### PR TITLE
feat(lint): add linting for docs

### PR DESCRIPTION
**Pull request by JaeAeich**
## Description
Since most of the documentation will be written in md and vue, eslint wouldn't necessarily work here, a better solution would be to use prettier. We will assume prettier to be our linter insted of a formatter.

This makes sense as the documentation has just started and adding a fomatter to it won't change alot of codebase.

### CODE REVIEW

**Review by git-anurag-hub — APPROVED** [review]

**Comment by git-anurag-hub** [comment]
Hey @JaeAeich, can you maybe merge this in #145 & fix the lint there too!

**Review by git-anurag-hub — CHANGES_REQUESTED** [review]
Hey @JaeAeich, can you maybe merge this in https://github.com/elixir-cloud-aai/cloud-components/pull/145 & fix the lint there too!

**Comment by JaeAeich** [comment]
Is this good?
@git-anurag-hub

**Review by git-anurag-hub — APPROVED** [review]

**Comment by git-anurag-hub** [comment]
Thanks a lot! @JaeAeich

**Pull request merged**
