### PR TITLE
fix: windows path issue

### PR DESCRIPTION
**Pull request by anuragxxd**
## Description

Fixes #(issue)

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

## Summary by Sourcery

This pull request addresses a path issue on Windows by introducing a new utility function `normalizePath` to ensure consistent use of POSIX path separators. The function is applied to relevant file paths in the build script to prevent errors related to path inconsistencies.

- **Bug Fixes**:
    - Fixed path issue on Windows by normalizing file paths to use POSIX separators.
- **Enhancements**:
    - Added a utility function `normalizePath` to handle path normalization across different operating systems.

### CODE REVIEW

**Comment by SalihuDickson** [comment]
@sivangbagri, i've just pushed a fix for the issue you've been having, please check if it works.

**Comment by sivangbagri** [comment]
Hii @SalihuDickson thanks for this but I am still facing the same error on building the design packages 
image

**Comment by SalihuDickson** [comment]
@sivangbagri, taking a look at the error now it seems this might be an issue with your node version. Please check it and if the version is lower than 18 then update it and rerun the dev script. I'll also add that as an engine requirement in the packageJson

**Comment by SalihuDickson** [comment]
@sivangbagri, from the error code it seems that your node does not understand the `assert` keyword.
It might be the case that you have multiple versions of node installed and are not using the most recent version in this dir.

If the above stated is not the case then can we perhaps schedule a video call for today or tomorrow so that I can get real-time feedback. 

And can you try building on your windows machine (not WSL), I've tried on mine and it seems to work fine, but I need a second opinion.

**Review by SalihuDickson — APPROVED** [review]

**Pull request merged**
