### PR TITLE
feat(ecc-client-ga4gh-tes): add publish scripts

### LINKED ISSUE #120: feat(ecc-client-ga4gh-tes): Add publish script for npm
## Description
The current `TES` package doesn't have a publish script. To make the package consumable, configure the package to be published npm.

## Possible solution(s)
Currently, the package ignores transpiled files, configure `package.json` to make it consumable. 

## Additional context
Currently all the components are being exported, ideally, we want the `app-author` to import only the component required, some changes in the file structure might be needed.

### PR DESCRIPTION
**Pull request by JaeAeich**
## Description
Setup package to be published on `npm`.

Fixes #120 

## Checklist

- [x] My code follows the [contributing guidelines][contributing] of this project.
- [x] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code in hard-to-understand areas.
- [x] I have updated the user-facing documentation to describe any new or changed behavior.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have not reduced the existing code coverage.

### CODE REVIEW

**Comment by JaeAeich** [comment]
@git-anurag-hub @SalihuDickson , Can you check this PR?
[This](https://www.npmjs.com/package/ecc-client-ga4gh-tes?activeTab=readme) is the test package I have created and [this](https://github.com/elixir-cloud-aai/cloud-components/pull/122) is the branch I did it on (pushed all the code in one commit :sweat_smile: )

The current issues I need an opinion on:
- FAST needs some wrapper to be used with [React](https://www.fast.design/docs/integrations/react). Since the comps must be cross-platform, how would I export the component? I will need to change the file str, too.
- Exports: The current way is exporting all the Web Components simultaneously. How to configure so that the only required comps get exported.
- Versioning and changelog: How to set up and define package versioning [here](https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing) (Maybe this could be another PR)?

**Review by SalihuDickson — COMMENTED** [review]
looks good so far. I have some minor fixes but I'll just make a PR to your branch. 

I think we also need to look into the downsides of registering a component in the packages instead of letting the developers do it before using them, I think it has negative effects on performance as it might impact how tree-shaking algorithms handle unused components. I'm not entirely sure so I think we should look into it before going one way or the other.

**Review by git-anurag-hub — APPROVED** [review]
This LGTM @JaeAeich! Can you delete the package from the npm named `ecc-client-ga4gh-tes` will publish the new package!

**Review by git-anurag-hub — APPROVED** [review]

**Comment by JaeAeich** [comment]
> This LGTM @JaeAeich! Can you delete the package from the npm named `ecc-client-ga4gh-tes` will publish the new package!

yeah sure!

**Pull request merged**
