### PR TITLE
feat: add common ESLint config

### LINKED ISSUE #21: feat: Implementing Common Linter Configuration
**Is your feature request related to a problem? Please describe.**

Currently, managing linters separately for each package/app within the project is proving to be difficult and time-consuming. To address this challenge, create the implementation of a common linter configuration that can be shared across all packages/apps.

**Describe the solution you'd like**
One recommended approach for achieving this is by adopting the guidelines provided by Turbo's documentation on linting with ESLint. The documentation offers a comprehensive handbook that outlines best practices for setting up a common linter configuration.

**Describe alternatives you've considered**
Maybe create the config in the root of the repo & apply it to all workspaces. But it will defeat the idea of customization of the workspace-specific linters.

**Additional context**
Please refer to the Turbo documentation on linting with ESLint (https://turbo.build/repo/docs/handbook/linting/eslint) for detailed instructions on how to set up the common linter configuration across your packages/apps.

Note:
While the Turbo documentation is recommended, you are free to explore alternative solutions or provide your own implementation suggestions if they better suit your project's requirements.

**Acknowledgement**

> We thank you for your valuable contribution and would like to acknowledge it
> on our [contributors][contributors] page. To help us with that, we would like
> to kindly request that you help us with this by commenting on this issue with
> a request to the [@all-contributors bot][all-contributors-bot] of the form
> `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1, TYPE_2, ...`, where
> `TYPE_1` etc. refer to [contribution types supported by the All Contributors
> Specification][all-contributors-types], e.g., `idea`.

[all-contributors-bot]: <https://allcontributors.org/docs/en/bot/overview>
[all-contributors-types]: <https://allcontributors.org/docs/en/emoji-key>
[contributors]: ../../CONTRIBUTORS

### PR DESCRIPTION
**Pull request by JaeAeich**
## Description

Added a common linter configuration package (Eslint) to streamline linting across the projects within this monorepo. The package offers a high-level linting configuration that can be easily extended and utilized to maintain consistent linting standards.

Fixes #21

## Checklist

> Please go through the following checklist to ensure that your change is ready
> for review. Please do not forget to double check the list after you have
> modified your PR, e.g., if you have added commits to address reviewer
> comments or to fix failing automated checks. Please check items also if they
> do not apply to your change, e.g., if your change does not require an update
> of the user-facing documentation, then still check the box. Generally, PRs
> are only reviewed when all boxes are ticked off and all automated checks pass
> (use the comment section below if you believe that your PR is ready to be
> merged even though not all boxes were ticked off).

- [x] My code follows the [contributing guidelines][contributing] of this
      project, including, in particular, with regard to any style guidelines
- [x] The title of my PR complies with the [Conventional Commits
      specification][conventional-commits]; in particular, it clearly indicates
      that a change is a breaking change
- [x] I am aware that all my commits will be squashed into a single commit,
      using the PR title as the commit message.
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have updated the user-facing documentation to describe any new or
      changed behavior
- [ ] I have added type annotations for all function/class/method interfaces
      or updated existing ones
- [ ] I have provided [JSDoc][jsdoc] block tags for all
      functions/classes/methods or updated existing ones
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage
- [x] I have asked the [@all-contributors bot][all-contributors-bot] to
      acknowledge my contributions by commenting on this PR with a request of
      the form `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1,
    TYPE_2, ...`, where `TYPE_1` etc. refer to [contribution types supported
      by the All Contributors Specification][all-contributors-types] OR I do
      not want my contributions to be acknowledged

## Comments

The unchecked boxes above are not required for this PR. 
@all-contributors please add @JaeAeich  for code.

[all-contributors-bot]: https://allcontributors.org/docs/en/bot/overview
[all-contributors-types]: https://allcontributors.org/docs/en/emoji-key
[contributing]: CONTRIBUTING.md
[conventional-commits]: https://www.conventionalcommits.org/en/v1.0.0/
[jsdoc]: https://jsdoc.app/index.html

### CODE REVIEW

**Review by uniqueg — CHANGES_REQUESTED** [review]
Thanks @JaeAeich, as far as I can tell, it looks good. But maybe @git-anurag-hub has some more comments.

One thing I was wondering: Wouldn't it be good to update the example package and app to make use of the common config?

**Comment by git-anurag-hub** [comment]
Is this a duplicate https://github.com/elixir-cloud-aai/cloud-components/pull/28? @JaeAeich

**Comment by uniqueg** [comment]
@JaeAeich: If you have an open PR and wanna change it, please just push new commits, the PR will automatically be updated. We are not losing information either: If we wanna look at the state of your branch before you pushed additional commits, we can just check out that state of the branch, or any other commit that we want.

Instead, opening another branch can lead to confusion, like it does here. I still don't know which PR you would prefer.

Note that sometimes, it can make sense to have multiple PRs. We frequently have this scenario in GA4GH, when there are multiple suggestions on how to change the specification to support useful features. Then it makes sense to work out _competing_ PRs, then compare and vote for them.

However, this is rare and really only for comparing different approaches of addressing an issue. Usually, we either already have agreed upon one way of doing a thing, or the requirement is sufficiently clear that we can test for it and we don't care too much about the way we get there. Or, as in this case, the requirement is rather vague, but the implementation is not overly consequential (like this one). In all of these cases, a single PR will do.

So, can you please bring one of the two PRs to the state that you want us to review (I see that they differ slightly) and then close the other one? :pray:

**Comment by JaeAeich** [comment]
Thanks @uniqueg for the clarification as this one doesn't contain example usage I will close it and request @git-anurag-hub to review the other one.

**Pull request closed without merging**
