### PR TITLE
fix: lint error

### PR DESCRIPTION
**Pull request by JaeAeich**
## Description

Eslint is throwing an unwanted, too-strict error since this error is just happening for a file, disabling it for the specific line makes more sense than disabeling it for entire package.

> The error for some reason is not visible on local, but can be simulated on local with exact same configuration as mentioned in CI, I did it on node-20:alpine image to check the trace of the issue as it was;t visible on the dev env.
## Checklist

- [x] My code follows the [contributing guidelines][contributing] of this project.
- [x] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code in hard-to-understand areas.
- [x] I have updated the user-facing documentation to describe any new or changed behavior.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by JaeAeich** [comment]
@SalihuDickson @git-anurag-hub @uniqueg Please review and approve this PR, it just ignore some eslint errors, shouldn't impact the functionality.

The error was too strict in forcing use of "this" keyword in this specific case and miscellaneous as it only popped in CI :man_shrugging:

**Comment by SalihuDickson** [comment]
With this you're disabling eslint entirely on a several lines, which is never advisable. This way we could miss other important linting issues and revisiting the issue to fix it later becomes difficult. Its best to figure out the issue, which in this case is a minor issue, so you can just convert it to a warning to make every violation easy to locate and address later
(depending on how important we consider strict modularization). 

My recent build scripts PR address this issue, you can still make a separate PR so this issue can be resolved quickly but this approach less than ideal.

**Comment by JaeAeich** [comment]
Yeah, makes sense the issue is Eslint is behaving weird here, I tried to figure out whats tripping eslint but since there are no trace in local environment, ie all the checks pass in in local but somehow seem to fail only in CI which I don't know why that's the case. Maybe you can take a look as well here.

**Comment by SalihuDickson** [comment]
Yh. I think there is a disparity in the dev and production rules. You can just change the code for `"class-methods-use-this"` rule to 1 (it currently defaults to 2) in the eslintrc for the lit tes package. That should fix it. 

You can use [this](https://github.com/elixir-cloud-aai/cloud-components/pull/229/commits/5d2f96d158556947f984b93a4bed1241fbb819b0) as a reference

**Comment by JaeAeich** [comment]
yeah I did try it, it doesn't seem to work that's why I had to disable it this way.

**Comment by JaeAeich** [comment]
@SalihuDickson maybe we can have it this way?

**Comment by SalihuDickson** [comment]
It works in my build scripts PR and again in [this](https://github.com/elixir-cloud-aai/cloud-components/tree/fix/lint-error) branch (i tried it again to isolate the solution). Perhaps is there something you could be doing wrong?

**Comment by JaeAeich** [comment]
> Yh. I think there is a disparity in the dev and production rules. You can just change the code for `"class-methods-use-this"` rule to 1 in the eslintrc for the lit tes package. That should fix it.
> 
> You can use [this](https://github.com/elixir-cloud-aai/cloud-components/pull/229/commits/5d2f96d158556947f984b93a4bed1241fbb819b0) as a reference

By I did I mean disabling individually. Having the eslint rule to turn this into a warning globally doesn't seem ideal to me, maybe when this rule will affect more than 3 files (rule of 3), we can think about that. What do you think?

**Comment by SalihuDickson** [comment]
Like I explained above, making it a warning for the entire package will ensure we can see whenever a file is breaking the rule. So it can easily be revisited later. Hiding catch-all one-liners in individual files will make this particular violation and others harder to catch later.

**Comment by JaeAeich** [comment]
__Closing this PR, please read the *above discussion* and checkout PR #236 :) !!__

**Pull request closed without merging**
