### PR TITLE
Fix: stop modifying packagejson

### PR DESCRIPTION
**Pull request by SalihuDickson**
## Description

This PR stops the build scripts from modifying the packagejson. Instead it tells the user the specific dependency that is missing and to install it. It also adds the necessary dependencies to the templates.

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by JaeAeich** [comment]
Hey @SalihuDickson just a question what's wrong with preinstalling these Dev deps in all the packages and leave it on the template file because we are sure that the new package will be installed from there. Because this government build script another task which it should be responsible for violating single responsibility principle. 
Correct me if I'm missing something, maybe this way is somehow better?

**Comment by SalihuDickson** [comment]
I added the dependencies to the template responsible for generating the packagejson file. I am verifying that they're installed for better error handling. Cause we don't want the scripts to throw a more cryptic error later.

**Comment by JaeAeich** [comment]
> Cause we don't want the scripts to throw a more cryptic error later, since the contributors could have modified the dependencies of their packages.

Makes sense, good point but lets say dev does modify it won't it show on the files changes :sweat_smile: . I just think *build* script should be responsible for such edge cases but I get you. Maybe @anuragxxd can also give his opinions here.

**Review by anuragxxd — APPROVED** [review]
lgtm

**Comment by anuragxxd** [comment]
> > Cause we don't want the scripts to throw a more cryptic error later, since the contributors could have modified the dependencies of their packages.
> 
> Makes sense, good point but lets say dev does modify it won't it show on the files changes 😅 . I just think _build_ script should be responsible for such edge cases but I get you. Maybe @anuragxxd can also give his opinions here.

I think @SalihuDickson solution is good for now. Moreover, it will give users flexibility over the versioning of their packages.

**Pull request merged**
