### PR TITLE
feat(ci): cache deps

### LINKED ISSUE #182: fix: CI cache
## Description

Cache the NPM dependencies to reduce the CI run minutes!

### PR DESCRIPTION
**Pull request by JaeAeich**
## Description

Cache dependencies for CI runs. This PR speeds up dependency installation by **~50%**. For more details checkout CI details of this PR or #235 (a test pr).

_This PR also bumps up node version for `release ci`._

Fixes #182

## Checklist

- [x] My code follows the [contributing guidelines][contributing] of this project.
- [x] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code in hard-to-understand areas.
- [x] I have updated the user-facing documentation to describe any new or changed behavior.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have not reduced the existing code coverage.

## Comments
image
_Previously deps installation took `more than min`._
image
_Installation time reduced to `27s`._
image

[contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by JaeAeich** [comment]
@git-anurag-hub please check the vercel failure or give me the logs.
@SalihuDickson @git-anurag-hub please review this.

**Review by uniqueg — COMMENTED** [review]
Good stuff! I guess you can merge from my side, after that Vercel stuff is fixed

**Comment by JaeAeich** [comment]
change in package.json is due to a recent PR not pushing lock file

**Review by SalihuDickson — COMMENTED** [review]
This looks good already, once we can get those logs, lgtm.

**Comment by JaeAeich** [comment]
@git-anurag-hub can you please re run vercel build.

**Review by git-anurag-hub — APPROVED** [review]

**Pull request merged**
