### PR TITLE
chore: configure commit templating

### LINKED ISSUE #29: feat: enforce commit message template
**Is your feature request related to a problem? Please describe.**
To improve tracking and visibility of the components developers are working on, it is essential to enforce a commit message template that includes component-specific information. By implementing this, we can easily identify the changes made to specific components within our codebase.

**Describe the solution you'd like**
Some points are:
- Adopt the conventional commit message format, which provides a standardized structure for commit messages (additional requirement: title lines of commit messages may not exceed 50 chars!)
- Configure a pre-commit hook script that runs before each commit and validates the commit message against the conventional commit message template. This script ensures that developers adhere to the defined format and include the necessary component information.
- Integrate the pre-commit hook script into the hooks directory of our version control system (e.g., Git).
- Document the conventional commit message format and the enforcement process in our project's documentation.

**Describe alternatives you've considered**
Not as such

**Additional context**
NA

**Acknowledgement**

> We thank you for your valuable contribution and would like to acknowledge it
> on our [contributors][contributors] page. To help us with that, we would like
> to kindly request that you help us with this by commenting on this issue with
> a request to the [@all-contributors bot][all-contributors-bot] of the form
> `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1, TYPE_2, ...`, where
> `TYPE_1` etc. refer to [contribution types supported by the All Contributors
> Specification][all-contributors-types], e.g., `idea`.

[all-contributors-bot]: <https://allcontributors.org/docs/en/bot/overview>
[all-contributors-types]: <https://allcontributors.org/docs/en/emoji-key>
[contributors]: ../../CONTRIBUTORS

### PR DESCRIPTION
**Pull request by git-anurag-hub**
## Description

Fixes #29 

## Checklist

> Please go through the following checklist to ensure that your change is ready
> for review. Please do not forget to double check the list after you have
> modified your PR, e.g., if you have added commits to address reviewer
> comments or to fix failing automated checks. Please check items also if they
> do not apply to your change, e.g., if your change does not require an update
> of the user-facing documentation, then still check the box. Generally, PRs
> are only reviewed when all boxes are ticked off and all automated checks pass
> (use the comment section below if you believe that your PR is ready to be
> merged even though not all boxes were ticked off).

- [ ] My code follows the [contributing guidelines][contributing] of this
      project, including, in particular, with regard to any style guidelines
- [ ] The title of my PR complies with the [Conventional Commits
      specification][conventional-commits]; in particular, it clearly indicates
      that a change is a breaking change
- [ ] I am aware that all my commits will be squashed into a single commit,
      using the PR title as the commit message.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have updated the user-facing documentation to describe any new or
      changed behavior
- [ ] I have added type annotations for all function/class/method interfaces
      or updated existing ones
- [ ] I have provided [JSDoc][jsdoc] block tags for all
      functions/classes/methods or updated existing ones
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature
      works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have not reduced the existing code coverage
- [ ] I have asked the [@all-contributors bot][all-contributors-bot] to
      acknowledge my contributions by commenting on this PR with a request of
      the form `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1,
    TYPE_2, ...`, where `TYPE_1` etc. refer to [contribution types supported
      by the All Contributors Specification][all-contributors-types] OR I do
      not want my contributions to be acknowledged

## Comments

> If there are unchecked boxes in the list above, but you would still like your
> PR to be reviewed or considered for merging, please describe here why boxes
> were not checked. For example, if you are positive that your commits should
> _not_ be squased when merging, please explain why you think the PR warrants
> or requires multiple commits to be added to the history.

[all-contributors-bot]: https://allcontributors.org/docs/en/bot/overview
[all-contributors-types]: https://allcontributors.org/docs/en/emoji-key
[contributing]: CONTRIBUTING.md
[conventional-commits]: https://www.conventionalcommits.org/en/v1.0.0/
[jsdoc]: https://jsdoc.app/index.html

### CODE REVIEW

**Review by uniqueg — CHANGES_REQUESTED** [review]
Can you somehow add a rule that commit title lines cannot be longer than 50 chars? Or is this a default anyways?

Also, please fix the conflict in `package.json`

**Comment by git-anurag-hub** [comment]
There is the default title size already configured! I think it was about 90 chars!

**Comment by uniqueg** [comment]
> There is the default title size already configured! I think it was about 90 chars! This is what it looks like https://github.com/commitizen/cz-cli#if-your-repo-is-commitizen-friendly

Okay, but can we change it to 50? :)

**Comment by git-anurag-hub** [comment]
Yeah, it can be done but it will require a little more config. We could have it as another issue along with proper templating of commit messages. Right now, this will provide the basic info to keep track. @uniqueg

**Comment by uniqueg** [comment]
Okay, fair enough. Do you wanna write a new issue and then merge?

**Review by uniqueg — APPROVED** [review]

**Comment by git-anurag-hub** [comment]
Closing this by creating this #33!

**Comment by git-anurag-hub** [comment]
@all-contributors please add @git-anurag-hub for infrastructure, idea, maintenance, code

**Pull request merged**
